sudo: required
services:
  - docker

script:
  - docker build -t anthony186/node .
  - docker images anthony186/node

before_deploy:
  - docker login -u anthony186 -p Huuhien18

deploy:
  provider: script
  script: docker push anthony186/node
  on:
    branch: master